<!DOCTYPE html>
<html lang='pt-br'>
<head>
	<meta charset="UTF-8">
	<title>Editar Estado</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
	
	<div class="container">
		<h2>Estado</h2>		

		<div class="row">
			<div class="col-md-8">
				<div class="panel panel-default">
					<div class="panel-body">
						
						<form action="/estado/<?= $estado->_id ?>/alterar" method="post">
							<div class="form-group">
								<label for="nome">Nome</label>
								<input type="text" class="form-control" name="nome" id="nome" placeholder="Nome" value="<?= $estado->nome ?>">
							</div>
							<div class="form-group">
								<label for="sigla">Sigla</label>
								<input type="text" class="form-control text-uppercase" name="sigla" id="sigla" placeholder="Sigla" maxlength="2" value="<?= $estado->sigla ?>">
							</div>
						  <button type="submit" class="btn btn-primary">Alterar</button>
						  <a href="/estado" alt="cancelar" class="btn btn-danger">Cancelar</a>	
						</form>
					
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>