<!DOCTYPE html>
<html lang='pt-br'>
<head>
	<meta charset="UTF-8">
	<title>Lista de Estados</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
	
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Estados</h2>
				<a href="/estado/cadastrar" alt="cadastrar" class="btn btn-success">Cadastrar</a>
				<div class="panel panel-default">
					<div class="panel-body">
						<table class="table">
							<thead>
								<tr>
									<th>#</th>
									<th>Nome</th>
									<th>Sigla</th>
									<th>Criado Em</th>
									<th>Última Atualização</th>
									<th>Ações</th>
								</tr>
							</thead>
							<tbody>
								<?php if (isset($estados)): foreach ($estados as $estado): ?>
								<tr>
									<td><?= $estado->_id ?></td>
									<td><?= $estado->nome ?></td>
									<td class="text-uppercase"><?= $estado->sigla ?></td>
									<td><?= $estado->criado_em ?></td>
									<td><?= $estado->atualizado_em ?></td>
									<td>
										<a href="/estado/<?= $estado->_id ?>/alterar" alt="alterar" class="btn btn-info">Editar</a>
										<a href="/estado/<?= $estado->_id ?>/excluir" alt="excluir" class="btn btn-danger">Excluir</a>
									</td>
								</tr>
								<?php endforeach; endif; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>